-- Migration 013: Retrospective pipeline tables
PRAGMA user_version = 13;

-- Sell audit results — one row per holding scored by the sell pipeline run
CREATE TABLE IF NOT EXISTS sell_audits (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    audit_id                 TEXT    NOT NULL UNIQUE,        -- "SAUDIT_{ts}_{symbol}_{rand}"
    audited_at               DATETIME NOT NULL,
    symbol                   TEXT    NOT NULL,
    instrument_token         INTEGER,
    sector                   TEXT,
    trading_mode             TEXT    NOT NULL DEFAULT 'simulator',
    user_id                  INTEGER REFERENCES users(id),

    -- Link to open trade if found (NULL if no matching open position)
    trade_id                 TEXT REFERENCES trades(trade_id),

    -- Snapshot at time of audit
    current_price            REAL,
    unrealized_pnl_pct       REAL,

    -- Technical snapshot
    rsi                      REAL,
    adx                      REAL,
    ema_20                   REAL,
    ema_50                   REAL,
    ema_200                  REAL,
    stock_3m_return          REAL,
    nifty_3m_return          REAL,
    sector_5d_change         REAL,

    -- Fundamental snapshot
    roe                      REAL,
    debt_to_equity           REAL,
    profit_declining_quarters INTEGER,

    -- Sell scoring
    urgency_score            INTEGER NOT NULL,               -- 0-100
    urgency_level            TEXT    NOT NULL,               -- HOLD | WATCH | SELL | STRONG SELL
    urgency_reasons          TEXT,                           -- JSON array of signal strings
    sell_score_breakdown     TEXT,                           -- JSON object of per-signal scores

    -- AI reasoning
    ai_reasoning             TEXT,                           -- Claude explanation (sell or hold)
    news_sentiment           INTEGER,                        -- 1-5
    news_flag                TEXT                            -- warning | clear
);

CREATE INDEX IF NOT EXISTS idx_sell_audits_symbol ON sell_audits(symbol);
CREATE INDEX IF NOT EXISTS idx_sell_audits_trade_id ON sell_audits(trade_id);
CREATE INDEX IF NOT EXISTS idx_sell_audits_audited_at ON sell_audits(audited_at);
CREATE INDEX IF NOT EXISTS idx_sell_audits_urgency ON sell_audits(urgency_level);

-- Link sell audit to the trade that was subsequently closed
ALTER TABLE trades ADD COLUMN exit_audit_id TEXT REFERENCES sell_audits(audit_id);
CREATE INDEX IF NOT EXISTS idx_trades_exit_audit ON trades(exit_audit_id);

-- Retrospective analysis reports — generated by the retrospective pipeline
CREATE TABLE IF NOT EXISTS retrospective_reports (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    report_id         TEXT    NOT NULL UNIQUE,               -- "RETRO_{ts}_{rand}"
    generated_at      DATETIME NOT NULL,
    trading_mode      TEXT    NOT NULL DEFAULT 'simulator',  -- simulator | live | all
    period_start      DATETIME NOT NULL,
    period_end        DATETIME NOT NULL,
    lookback_days     INTEGER NOT NULL,

    -- Coverage stats
    trades_analyzed   INTEGER NOT NULL DEFAULT 0,
    winners           INTEGER NOT NULL DEFAULT 0,
    losers            INTEGER NOT NULL DEFAULT 0,
    win_rate_pct      REAL,
    total_pnl         REAL,
    avg_pnl_pct       REAL,

    -- Stage outputs (JSON blobs — each is the structured output of one retrospective stage)
    cohort_aggregates  TEXT,   -- JSON: aggregates by gear/conviction/trigger/sector
    winner_patterns    TEXT,   -- JSON: {patterns, cited_trades}
    loser_patterns     TEXT,   -- JSON: {patterns, cited_trades}
    filter_audit       TEXT,   -- JSON: per-stage tightness verdict
    sl_calibration     TEXT,   -- JSON: per-gear multiplier findings
    conviction_cal     TEXT,   -- JSON: conviction predictiveness + composite score cal
    sell_audit_cal     TEXT,   -- JSON: audit accuracy findings

    -- Final synthesized output
    claude_findings        TEXT,                             -- Markdown narrative
    claude_recommendations TEXT,                             -- JSON array: [{parameter, current_value, suggested_value, reasoning, confidence, supporting_stages, cited_trades}]

    triggered_by      TEXT    NOT NULL DEFAULT 'manual',     -- manual | monthly_cron
    user_id           INTEGER REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_retro_reports_generated_at ON retrospective_reports(generated_at);
CREATE INDEX IF NOT EXISTS idx_retro_reports_mode ON retrospective_reports(trading_mode);
